export const stock = [
  {
    id: 1,
    price: 15,
    band: "blink182",
    album: "Nine",
    tracks: [
      "The First Time : 3:06",
      "Happy Days : 3:59",
      "Heaven : 3:17",
      "Darkside : 3:00",
      "Blame It on My Youth : 3:05",
      "Generational Divide : 0:49",
      "Run Away : 3:01",
      "Black Rain : 2:46",
      "I Really Wish I Hated You : 3:11",
      "Pin the Grenade : 3:59",
      "No Heart to Speak Of : 3:40",
      "Ransom : 2:53",
      "On Some Emo S*** : 3:00",
      "Hungover You : 3:56",
      "Remember to Forget Me : 3:30",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5eb33639aaeecfcc5ebada97476", //640 Height 640 Width inital
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b273198542728b101474c4afe0a1",
    smAlbumImage:
      "https://i.scdn.co/image/ab67616d00004851198542728b101474c4afe0a1",
    about:
      "Nine is the eighth studio album by American rock band Blink-182, released on September 20, 2019, through Columbia Records, as the band's first album on the label.",
    quantity: 1,
  },
  {
    id: 2,
    price: 10,
    band: "yellowcard",
    album: "Ocean avenue",
    tracks: [
      "Way Away : 3:23",
      "Breathing : 3:38",
      "Ocean Avenue : 3:19",
      "Empty Apartment : 3:36",
      "Life of a Salesman : 3:18",
      "Only One : 4:17",
      "Miles Apart : 3:31",
      "Twentythree : 4:04",
      "View from Heaven : 3:23",
      "Inside Out : 3:39",
      "Believe : 4:32",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5eb952381a70ceeda02554ad545",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b273d1fd8f264564d9eef7617a45",
    about:
      "Ocean Avenue is the fourth studio album by American rock band Yellowcard, released on July 22, 2003, through Capitol Records, featuring the hit single of the same name and becoming the band's breakthrough album.",
    quantity: 1,
  },
  {
    id: 3,
    price: 21,
    band: "Green day",
    album: "Dookie",
    tracks: [
      "Burnout : 2:07",
      "Having a Blast : 2:45",
      "Chump : 2:54",
      "Longview : 3:59",
      "Welcome to Paradise : 3:45",
      "Pulling Teeth : 2:31",
      "Basket Case : 3:01",
      "She : 2:14",
      "Sassafras Roots : 2:38",
      "When I Come Around : 2:58",
      "Coming Clean : 1:34",
      "Emenius Sleepus : 1:44",
      "In the End : 1:46",
      "F.O.D. : 5:46",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5eb047eac333eff0be4abe32cbf",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b273db89b08034de626ebee6823d",
    about:
      "Dookie is the third studio album by American punk rock band Green Day, released on February 1, 1994, through Reprise Records, featuring the hit singles 'Longview', 'Basket Case', and 'When I Come Around', and becoming a defining album of the punk rock genre.",

    quantity: 1,
  },
  {
    id: 4,
    price: 20,
    band: "blink182",
    album: "Untitled",
    tracks: [
      "Feeling This : 2:53",
      "Obvious : 2:43",
      "I Miss You : 3:47",
      "Violence : 3:40",
      "Stockholm Syndrome : 2:42",
      "Down : 3:03",
      "The Fallen Interlude : 2:13",
      "Go : 1:53",
      "Asthenia : 4:19",
      "Always : 4:12",
      "Easy Target : 2:20",
      "All of This : 4:40",
      "Here's Your Letter : 2:54",
      "I'm Lost Without You : 6:21",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5eb33639aaeecfcc5ebada97476",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b2730538b48c180256e0bdd8363f",
    about:
      "Untitled, commonly referred to as Blink-182, is the band's eponymous sixth studio album, released on November 18, 2003, featuring a darker and more experimental sound than their previous works.",
    quantity: 1,
  },
  {
    id: 5,
    price: 15,
    band: "The Beatles",
    album: "Revolver",
    tracks: [
      "Taxman : 2:39",
      "Eleanor Rigby : 2:06",
      "I'm Only Sleeping : 3:02",
      "Love You To : 3:01",
      "Here, There and Everywhere : 2:25",
      "Yellow Submarine : 2:40",
      "She Said She Said : 2:37",
      "Good Day Sunshine : 2:09",
      "And Your Bird Can Sing : 2:02",
      "For No One : 2:01",
      "Doctor Robert : 2:15",
      "I Want to Tell You : 2:29",
      "Got to Get You into My Life : 2:31",
      "Tomorrow Never Knows : 3:00",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5ebe9348cc01ff5d55971b22433",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b27328b8b9b46428896e6491e97a",
    about:
      "Revolver is the seventh studio album by the iconic British rock band, The Beatles, released on August 5, 1966. It marked a significant shift in their sound, embracing innovative recording techniques and showcasing their evolving musical experimentation, solidifying its status as one of the greatest and most influential albums in the history of popular music.",
    quantity: 1,
  },
  {
    id: 6,
    price: 17,
    band: "The Beatles",
    album: "Abbey Road",
    tracks: [
      "Come Together : 4:20",
      "Something : 3:03",
      "Maxwell's Silver Hammer : 3:27",
      "Oh! Darling : 3:26",
      "Octopus's Garden : 2:51",
      "I Want You (She's So Heavy) : 7:47",
      "Here Comes the Sun : 3:05",
      "Because : 2:45",
      "You Never Give Me Your Money : 4:02",
      "Sun King : 2:26",
      "Mean Mr. Mustard : 1:06",
      "Polythene Pam : 1:13",
      "She Came In Through the Bathroom Window : 1:57",
      "Golden Slumbers : 1:31",
      "Carry That Weight : 1:36",
      "The End : 2:20",
      "Her Majesty : 0:23",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5ebe9348cc01ff5d55971b22433",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b273dc30583ba717007b00cceb25",
    about:
      "Abbey Road is the eleventh studio album by The Beatles, released on September 26, 1969. It was the last album recorded by the band before their dissolution and is widely regarded as one of their finest works, featuring iconic tracks such as 'Come Together,' 'Here Comes the Sun,' and the legendary medley on Side B, making it a timeless masterpiece in the realm of rock music.",
    quantity: 1,
  },
  {
    id: 7,
    price: 13,
    band: "The Beatles",
    album: "Help!",
    tracks: [
      "Help! : 2:18",
      "The Night Before : 2:36",
      "You've Got to Hide Your Love Away : 2:09",
      "I Need You : 2:31",
      "Another Girl : 2:05",
      "You're Going to Lose That Girl : 2:18",
      "Ticket to Ride : 3:10",
      "Act Naturally : 2:30",
      "It's Only Love : 1:55",
      "You Like Me Too Much : 2:35",
      "Tell Me What You See : 2:36",
      "I've Just Seen a Face : 2:05",
      "Yesterday : 2:05",
      "Dizzy Miss Lizzy : 2:53",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5ebe9348cc01ff5d55971b22433",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b273e3e3b64cea45265469d4cafa",
    about:
      "Help! is the fifth studio album by The Beatles, released on August 6, 1965. It served as the soundtrack to the film of the same name and showcased the band's transition into a more mature sound and introspective lyrics. Featuring hits like the title track and 'Ticket to Ride,' Help! remains a pivotal album in The Beatles' discography, showcasing their musical growth and expanding their creative boundaries.",
    quantity: 1,
  },
  {
    id: 8,
    price: 15,
    band: "A Day To Remember",
    album: "Homesick",
    tracks: [
      "The Downfall of Us All : 3:29",
      "My Life for Hire : 3:34",
      "I'm Made of Wax, Larry, What Are You Made Of? : 3:00",
      "NJ Legion Iced Tea : 3:32",
      "Mr. Highway's Thinking About the End : 4:01",
      "Have Faith in Me : 3:08",
      "Welcome to the Family : 3:10",
      "Homesick : 3:58",
      "Holdin' It Down for the Underground : 3:25",
      "You Already Know What You Are : 1:21",
      "Another Song About the Weekend : 3:46",
      "If It Means a Lot to You : 4:03",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5eba782bcfcb0819c20e99d8315",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b2730b02af77159866fe3e011c76",
    about:
      "Homesick is the third studio album by American rock band A Day to Remember, released on February 3, 2009. It is a powerful blend of pop punk and metalcore, showcasing the band's signature style and introspective lyrics. Homesick gained widespread acclaim, featuring notable tracks such as 'The Downfall of Us All' and 'If It Means a Lot to You,' solidifying A Day to Remember's status as one of the leading acts in the genre.",
    quantity: 1,
  },
  {
    id: 9,
    price: 19,
    band: "A Day To Remember",
    album: "Common Courtesy",
    tracks: [
      "City of Ocala : 3:25",
      "Right Back at It Again : 3:14",
      "Sometimes You're the Hammer, Sometimes You're the Nail : 4:35",
      "Dead & Buried : 3:15",
      "Best of Me : 3:28",
      "I'm Already Gone : 4:04",
      "Violence (Enough Is Enough) : 4:16",
      "Life Lessons Learned the Hard Way : 2:56",
      "End of Me : 3:58",
      "The Document Speaks for Itself : 2:54",
      "I Remember : 4:00",
      "Leave All the Lights On : 3:17",
      "Good Things : 3:41",
      "Same Book but Never the Same Page : 3:37",
      "The Worst of Them : 3:52",
      "I Surrender : 3:34",
      "Life @ 11 : 3:21",
      "I'm Already Gone (Acoustic) : 3:53",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5eba782bcfcb0819c20e99d8315",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b273faa5f77ae241454fae86d480",
    about:
      "Common Courtesy is the fifth studio album by American rock band A Day to Remember, independently released on October 8, 2013. It was a highly anticipated album, as it was self-funded and self-released by the band after a legal dispute with their record label. Common Courtesy showcases A Day to Remember's signature blend of pop punk and metalcore, delivering anthemic tracks like 'Right Back at It Again' and 'I Remember,' reaffirming their resilience and dedication to their craft.",
    quantity: 1,
  },
  {
    id: 10,
    price: 22,
    band: "Fleetwood Mac",
    album: "Rumours",
    tracks: [
      "Second Hand News : 2:56",
      "Dreams : 4:14",
      "Never Going Back Again : 2:14",
      "Don't Stop : 3:13",
      "Go Your Own Way : 3:43",
      "Songbird : 3:20",
      "The Chain : 4:30",
      "You Make Loving Fun : 3:31",
      "I Don't Want to Know : 3:15",
      "Oh Daddy : 3:56",
      "Gold Dust Woman : 4:56",
    ],
    bandImage:
      "https://i.scdn.co/image/ab6761610000e5eb249d55f2d68a44637905c57e",
    albumImage:
      "https://i.scdn.co/image/ab67616d0000b2730001af4f80be77069fc8fd41",
    about:
      "Rumours is the eleventh studio album by British-American rock band Fleetwood Mac, released on February 4, 1977. It became a monumental success, propelled by its emotionally charged songs and intricate harmonies. Rumours delved into the personal lives of the band members, reflecting their turbulent relationships and resulting in iconic tracks like 'Go Your Own Way,' 'Dreams,' and 'Don't Stop.' With its timeless sound and enduring popularity, Rumours is widely regarded as one of the greatest albums of all time.",
    quantity: 1,
  },
];
